import Foundation

/// Service providing the complete catalog of birds available in BirdVault.
/// Contains real North American bird species data.
final class BirdDataService {
    static let shared = BirdDataService()

    private(set) var allBirds: [Bird] = []
    private var birdsByID: [String: Bird] = [:]

    private init() {
        loadBirds()
    }

    func bird(for id: String) -> Bird? {
        birdsByID[id]
    }

    func birds(for region: BirdRegion) -> [Bird] {
        allBirds.filter { $0.regions.contains(region) || $0.regions.contains(.nationwide) }
    }

    func birds(for season: Season) -> [Bird] {
        allBirds.filter { $0.seasonalPresence.contains(season) || $0.seasonalPresence.contains(.yearRound) }
    }

    func birds(matching query: String) -> [Bird] {
        let lowered = query.lowercased()
        return allBirds.filter {
            $0.commonName.lowercased().contains(lowered) ||
            $0.scientificName.lowercased().contains(lowered) ||
            $0.family.lowercased().contains(lowered)
        }
    }

    func birds(forRegion region: BirdRegion, season: Season) -> [Bird] {
        allBirds.filter { bird in
            (bird.regions.contains(region) || bird.regions.contains(.nationwide)) &&
            (bird.seasonalPresence.contains(season) || bird.seasonalPresence.contains(.yearRound))
        }
    }

    func currentSeason() -> Season {
        let month = Calendar.current.component(.month, from: Date())
        switch month {
        case 3...5: return .spring
        case 6...8: return .summer
        case 9...11: return .fall
        default: return .winter
        }
    }

    private func loadBirds() {
        allBirds = Self.birdCatalog
        for bird in allBirds {
            birdsByID[bird.id] = bird
        }
    }
}

// MARK: - Complete Bird Catalog
extension BirdDataService {
    static let birdCatalog: [Bird] = [
        // ── Cardinals & Grosbeaks ──────────────────────────────
        Bird(
            id: "northern_cardinal",
            commonName: "Northern Cardinal",
            scientificName: "Cardinalis cardinalis",
            family: "Cardinalidae",
            order: "Passeriformes",
            description: "One of America's most recognizable songbirds, known for its brilliant red plumage and distinctive crest.",
            habitat: "Woodlands, gardens, shrublands, and wetlands",
            diet: "Seeds, berries, and insects",
            funFact: "Northern Cardinals are one of the few species where the female also sings, often from the nest.",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest, .greatPlains, .texas],
            rarityTier: .common,
            hasSexualDimorphism: true,
            maleDescription: "Brilliant red plumage with a black face mask and prominent crest",
            femaleDescription: "Warm brown with reddish tinges on wings, tail, and crest",
            seasonalPresence: [.yearRound],
            sizeCategory: .small,
            primaryColors: [.red, .black, .brown],
            song: "A series of clear, sharp whistles: 'cheer-cheer-cheer' or 'birdy-birdy-birdy'"
        ),
        Bird(
            id: "rose_breasted_grosbeak",
            commonName: "Rose-breasted Grosbeak",
            scientificName: "Pheucticus ludovicianus",
            family: "Cardinalidae",
            order: "Passeriformes",
            description: "A striking songbird with a beautiful rose-red breast patch and melodious song.",
            habitat: "Deciduous and mixed forests, orchards, and parks",
            diet: "Insects, seeds, and berries",
            funFact: "Males share incubation duties and even sing while sitting on the nest!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .midwest, .greatPlains],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Black head and back, white underparts with a vivid rose-red breast patch",
            femaleDescription: "Brown-streaked with a bold white eyebrow stripe, resembling a large sparrow",
            seasonalPresence: [.spring, .summer],
            sizeCategory: .medium,
            primaryColors: [.black, .white, .red],
            song: "A rich, melodious warble similar to a robin but sweeter and more polished"
        ),

        // ── Jays & Corvids ────────────────────────────────────
        Bird(
            id: "blue_jay",
            commonName: "Blue Jay",
            scientificName: "Cyanocitta cristata",
            family: "Corvidae",
            order: "Passeriformes",
            description: "A bold, intelligent bird known for its striking blue coloring and loud calls.",
            habitat: "Forests, parks, and suburban areas",
            diet: "Nuts, seeds, insects, and occasionally eggs",
            funFact: "Blue Jays can mimic the calls of hawks, possibly to scare other birds away from food sources.",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest, .greatPlains],
            rarityTier: .common,
            hasSexualDimorphism: false,
            maleDescription: "Bright blue crest, back, and wings with white and black barring, gray-white underparts",
            femaleDescription: "Identical to males - both sexes share the same striking blue plumage",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.blue, .white, .black],
            song: "Loud 'jay-jay' calls and a variety of musical notes and mimicry"
        ),
        Bird(
            id: "american_crow",
            commonName: "American Crow",
            scientificName: "Corvus brachyrhynchos",
            family: "Corvidae",
            order: "Passeriformes",
            description: "Highly intelligent and adaptable, one of the most widespread birds in North America.",
            habitat: "Nearly everywhere: cities, farms, forests, and beaches",
            diet: "Omnivorous - eats almost anything",
            funFact: "Crows can recognize individual human faces and remember them for years.",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .common,
            hasSexualDimorphism: false,
            maleDescription: "Entirely black plumage with a glossy purple-blue sheen",
            femaleDescription: "Identical to males - sleek, all-black plumage",
            seasonalPresence: [.yearRound],
            sizeCategory: .large,
            primaryColors: [.black],
            song: "The familiar 'caw-caw-caw' plus a wide variety of clicks and rattles"
        ),
        Bird(
            id: "stellers_jay",
            commonName: "Steller's Jay",
            scientificName: "Cyanocitta stelleri",
            family: "Corvidae",
            order: "Passeriformes",
            description: "The western counterpart to the Blue Jay, with a dramatic dark crest and deep blue body.",
            habitat: "Coniferous and mixed forests in mountainous regions",
            diet: "Seeds, nuts, berries, insects, and small vertebrates",
            funFact: "Steller's Jays are skilled mimics and frequently imitate the calls of Red-tailed Hawks.",
            conservationStatus: .leastConcern,
            regions: [.west, .northwest, .california],
            rarityTier: .common,
            hasSexualDimorphism: false,
            maleDescription: "Black head and crest with deep blue body, wings, and tail",
            femaleDescription: "Very similar to male, slightly duller blue tones",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.blue, .black],
            song: "Harsh 'shaack-shaack-shaack' calls and quiet warbling songs"
        ),

        // ── Woodpeckers ───────────────────────────────────────
        Bird(
            id: "downy_woodpecker",
            commonName: "Downy Woodpecker",
            scientificName: "Dryobates pubescens",
            family: "Picidae",
            order: "Piciformes",
            description: "The smallest and most common woodpecker in North America, a frequent backyard visitor.",
            habitat: "Open woodlands, orchards, parks, and suburbs",
            diet: "Insects, seeds, and suet",
            funFact: "Despite their small size, Downy Woodpeckers drum on resonant branches at about 15 beats per second.",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .common,
            hasSexualDimorphism: true,
            maleDescription: "Black and white striped pattern with a small red patch on the back of the head",
            femaleDescription: "Same black and white pattern but lacks the red head patch",
            seasonalPresence: [.yearRound],
            sizeCategory: .small,
            primaryColors: [.black, .white, .red],
            song: "A sharp 'pik' call and a descending whinny rattle"
        ),
        Bird(
            id: "pileated_woodpecker",
            commonName: "Pileated Woodpecker",
            scientificName: "Dryocopus pileatus",
            family: "Picidae",
            order: "Piciformes",
            description: "The largest woodpecker in North America (excluding the likely extinct Ivory-billed), with a spectacular red crest.",
            habitat: "Mature deciduous and coniferous forests",
            diet: "Carpenter ants, wood-boring beetle larvae, fruits, and nuts",
            funFact: "Their rectangular excavations in dead trees are so large that they can cause small trees to break in half!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest, .northwest],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Mostly black with a flaming red crest, white neck stripes, and red mustache stripe",
            femaleDescription: "Similar to male but has a black forehead and no red mustache stripe",
            seasonalPresence: [.yearRound],
            sizeCategory: .large,
            primaryColors: [.black, .red, .white],
            song: "A loud, resonant 'wuk-wuk-wuk-wuk' that carries through the forest"
        ),
        Bird(
            id: "red_bellied_woodpecker",
            commonName: "Red-bellied Woodpecker",
            scientificName: "Melanerpes carolinus",
            family: "Picidae",
            order: "Piciformes",
            description: "A common eastern woodpecker with a misleading name - the red belly is usually hidden.",
            habitat: "Woodlands, suburbs, and parks",
            diet: "Insects, fruits, nuts, and seeds",
            funFact: "They store food by wedging it into bark crevices, including live grasshoppers!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest, .texas],
            rarityTier: .common,
            hasSexualDimorphism: true,
            maleDescription: "Zebra-striped black and white back, red crown extending to the nape",
            femaleDescription: "Similar striped pattern but red only on the nape, not the crown",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.red, .black, .white],
            song: "A rolling 'kwirr' call and sharp 'cha-cha-cha'"
        ),

        // ── Raptors ───────────────────────────────────────────
        Bird(
            id: "bald_eagle",
            commonName: "Bald Eagle",
            scientificName: "Haliaeetus leucocephalus",
            family: "Accipitridae",
            order: "Accipitriformes",
            description: "America's national bird and a powerful symbol of the wild, making a remarkable comeback from near extinction.",
            habitat: "Near large bodies of water with tall trees for nesting",
            diet: "Fish, waterfowl, and carrion",
            funFact: "Bald Eagle nests can weigh over 2 tons and be used for decades, growing larger each year.",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .rare,
            hasSexualDimorphism: true,
            maleDescription: "Dark brown body with distinctive white head and tail, yellow beak (adults)",
            femaleDescription: "Same plumage as male but noticeably larger - up to 25% bigger",
            seasonalPresence: [.yearRound],
            sizeCategory: .veryLarge,
            primaryColors: [.brown, .white, .yellow],
            song: "A surprisingly weak, high-pitched chattering whistle for such a large bird"
        ),
        Bird(
            id: "red_tailed_hawk",
            commonName: "Red-tailed Hawk",
            scientificName: "Buteo jamaicensis",
            family: "Accipitridae",
            order: "Accipitriformes",
            description: "North America's most common hawk, frequently seen soaring over open country and perched on highway signs.",
            habitat: "Open country, woodlands, prairies, and urban areas",
            diet: "Rodents, rabbits, snakes, and other small animals",
            funFact: "The Red-tailed Hawk's scream is the Hollywood 'eagle' sound - it's dubbed over Bald Eagle footage in movies!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Brown above, pale below with a streaked belly band and rusty-red tail",
            femaleDescription: "Similar to male but larger, slightly heavier streaking",
            seasonalPresence: [.yearRound],
            sizeCategory: .large,
            primaryColors: [.brown, .red, .white],
            song: "A piercing, descending scream: 'keeeeee-aarrr'"
        ),
        Bird(
            id: "peregrine_falcon",
            commonName: "Peregrine Falcon",
            scientificName: "Falco peregrinus",
            family: "Falconidae",
            order: "Falconiformes",
            description: "The fastest animal on Earth, capable of diving at speeds over 240 mph.",
            habitat: "Cliffs, tall buildings, bridges, and open areas near water",
            diet: "Medium-sized birds caught in flight",
            funFact: "During a hunting stoop (dive), Peregrines can exceed 240 mph, making them the fastest animals on Earth!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .rare,
            hasSexualDimorphism: true,
            maleDescription: "Blue-gray above, barred white below, with a distinctive black 'helmet' and mustache mark",
            femaleDescription: "Similar pattern but significantly larger and more heavily marked",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.gray, .white, .black],
            song: "A loud, rapid 'kak-kak-kak' alarm call near the nest"
        ),
        Bird(
            id: "great_horned_owl",
            commonName: "Great Horned Owl",
            scientificName: "Bubo virginianus",
            family: "Strigidae",
            order: "Strigiformes",
            description: "A powerful nocturnal predator and one of the most widespread owls in the Americas.",
            habitat: "Forests, deserts, swamps, and urban parks",
            diet: "Mammals, birds, reptiles - will even take skunks and porcupines",
            funFact: "Great Horned Owls have a grip strength of about 300 PSI - similar to a large dog's bite force!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Mottled gray-brown with prominent ear tufts, yellow eyes, and white throat patch",
            femaleDescription: "Similar but larger, sometimes with more rufous coloring",
            seasonalPresence: [.yearRound],
            sizeCategory: .large,
            primaryColors: [.brown, .gray, .yellow],
            song: "The classic deep hooting: 'hoo-hoo-hoooooo hoo-hoo' (5 hoots)"
        ),
        Bird(
            id: "barred_owl",
            commonName: "Barred Owl",
            scientificName: "Strix varia",
            family: "Strigidae",
            order: "Strigiformes",
            description: "A large, stocky owl with soulful dark eyes and the memorable 'Who cooks for you?' call.",
            habitat: "Dense forests, wooded swamps, and streamside woods",
            diet: "Small mammals, birds, amphibians, fish, and invertebrates",
            funFact: "Barred Owls are expanding westward and outcompeting the endangered Spotted Owl.",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest, .northwest],
            rarityTier: .uncommon,
            hasSexualDimorphism: false,
            maleDescription: "Brown and white barred plumage, round head with no ear tufts, dark brown eyes",
            femaleDescription: "Virtually identical to male, slightly larger",
            seasonalPresence: [.yearRound],
            sizeCategory: .large,
            primaryColors: [.brown, .white],
            song: "'Who cooks for you? Who cooks for you-all?' - a distinctive 8-note hooting"
        ),

        // ── Hummingbirds ──────────────────────────────────────
        Bird(
            id: "ruby_throated_hummingbird",
            commonName: "Ruby-throated Hummingbird",
            scientificName: "Archilochus colubris",
            family: "Trochilidae",
            order: "Apodiformes",
            description: "The only breeding hummingbird in eastern North America, a tiny jewel of the bird world.",
            habitat: "Gardens, forest edges, and meadows",
            diet: "Nectar, small insects, and spiders",
            funFact: "They beat their wings about 53 times per second and can fly backwards and upside down!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest, .texas],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Iridescent green above, white below, with a brilliant ruby-red throat (gorget)",
            femaleDescription: "Green above, white below, with no red throat - plain white throat instead",
            seasonalPresence: [.spring, .summer, .fall],
            sizeCategory: .tiny,
            primaryColors: [.green, .red, .iridescent],
            song: "Rapid squeaky chips and a mouse-like twittering"
        ),
        Bird(
            id: "annas_hummingbird",
            commonName: "Anna's Hummingbird",
            scientificName: "Calypte anna",
            family: "Trochilidae",
            order: "Apodiformes",
            description: "A year-round West Coast resident and one of the most vocal hummingbirds.",
            habitat: "Gardens, parks, coastal scrub, and open woodlands",
            diet: "Nectar, insects, and tree sap",
            funFact: "During courtship dives, males reach speeds that subject them to nearly 10 G-forces!",
            conservationStatus: .leastConcern,
            regions: [.west, .california, .northwest],
            rarityTier: .common,
            hasSexualDimorphism: true,
            maleDescription: "Green back with an iridescent magenta-rose crown and gorget",
            femaleDescription: "Green above, grayish below with small patches of iridescent red on throat",
            seasonalPresence: [.yearRound],
            sizeCategory: .tiny,
            primaryColors: [.green, .red, .iridescent],
            song: "A buzzy, scratchy song from a high perch - unusual for hummingbirds"
        ),

        // ── Warblers ──────────────────────────────────────────
        Bird(
            id: "yellow_warbler",
            commonName: "Yellow Warbler",
            scientificName: "Setophaga petechia",
            family: "Parulidae",
            order: "Passeriformes",
            description: "A bright splash of sunshine in summer willow thickets, one of the most widespread warblers.",
            habitat: "Wet thickets, edges of marshes, streams, and gardens",
            diet: "Insects and caterpillars",
            funFact: "When Brown-headed Cowbirds lay eggs in their nests, Yellow Warblers build a new floor over them and start again!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Bright yellow overall with bold reddish-brown streaks on the breast",
            femaleDescription: "Yellow-green overall, paler than male, with faint or no breast streaks",
            seasonalPresence: [.spring, .summer],
            sizeCategory: .small,
            primaryColors: [.yellow, .green],
            song: "'Sweet-sweet-sweet, I'm-so-sweet!' - a cheerful, rapid song"
        ),
        Bird(
            id: "black_throated_blue_warbler",
            commonName: "Black-throated Blue Warbler",
            scientificName: "Setophaga caerulescens",
            family: "Parulidae",
            order: "Passeriformes",
            description: "A strikingly dimorphic warbler where males and females look like entirely different species.",
            habitat: "Dense undergrowth in deciduous and mixed forests",
            diet: "Insects, spiders, and some berries in fall",
            funFact: "Males and females look so different that they were once classified as separate species!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Deep midnight blue above, white below, with a black face, throat, and sides",
            femaleDescription: "Olive-brown above, buffy below - looks completely different from the male",
            seasonalPresence: [.spring, .summer],
            sizeCategory: .small,
            primaryColors: [.blue, .black, .white],
            song: "A lazy, buzzy 'I am so la-zeee' rising at the end"
        ),

        // ── Thrushes ──────────────────────────────────────────
        Bird(
            id: "american_robin",
            commonName: "American Robin",
            scientificName: "Turdus migratorius",
            family: "Turdidae",
            order: "Passeriformes",
            description: "America's beloved herald of spring, known for running across lawns in search of earthworms.",
            habitat: "Lawns, gardens, parks, forests, and fields",
            diet: "Earthworms, insects, and berries",
            funFact: "Robins can actually see earthworms underground by tilting their heads to use one eye's superior vision!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .common,
            hasSexualDimorphism: true,
            maleDescription: "Dark gray-black head and back with a warm brick-red breast and yellow bill",
            femaleDescription: "Paler overall with a lighter orange breast and grayish head",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.red, .gray, .black],
            song: "A cheerful, caroling 'cheerily, cheer-up, cheerio' at dawn and dusk"
        ),
        Bird(
            id: "eastern_bluebird",
            commonName: "Eastern Bluebird",
            scientificName: "Sialia sialis",
            family: "Turdidae",
            order: "Passeriformes",
            description: "A symbol of happiness, this brilliant blue and rusty songbird thrives in open habitats with nest boxes.",
            habitat: "Open woodlands, farmlands, orchards, and parks with nest boxes",
            diet: "Insects and berries",
            funFact: "Bluebird populations crashed in the mid-1900s but recovered dramatically thanks to volunteer nest box trails!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest, .greatPlains],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Vivid royal blue above with a rusty-orange breast and white belly",
            femaleDescription: "Grayish-blue above with a muted orange breast, more subdued overall",
            seasonalPresence: [.yearRound],
            sizeCategory: .small,
            primaryColors: [.blue, .orange, .white],
            song: "A soft, musical 'tru-lee, tru-lee' warble"
        ),
        Bird(
            id: "wood_thrush",
            commonName: "Wood Thrush",
            scientificName: "Hylocichla mustelina",
            family: "Turdidae",
            order: "Passeriformes",
            description: "Possessor of one of the most beautiful songs in North America, a voice of the deep forest.",
            habitat: "Interior of mature deciduous and mixed forests",
            diet: "Insects, snails, and berries",
            funFact: "Wood Thrushes can sing two notes simultaneously using both sides of their syrinx!",
            conservationStatus: .nearThreatened,
            regions: [.northeast, .southeast, .midwest],
            rarityTier: .uncommon,
            hasSexualDimorphism: false,
            maleDescription: "Warm reddish-brown above, white with bold dark spots below, large eye-ring",
            femaleDescription: "Identical to male in plumage",
            seasonalPresence: [.spring, .summer],
            sizeCategory: .medium,
            primaryColors: [.brown, .white],
            song: "Ethereal flute-like phrases: 'ee-oh-lay' - widely considered the most beautiful American birdsong"
        ),

        // ── Finches ───────────────────────────────────────────
        Bird(
            id: "american_goldfinch",
            commonName: "American Goldfinch",
            scientificName: "Spinus tristis",
            family: "Fringillidae",
            order: "Passeriformes",
            description: "A bright, acrobatic finch that transforms from drab winter plumage to stunning summer gold.",
            habitat: "Weedy fields, roadsides, gardens, and open areas",
            diet: "Seeds, especially thistle and sunflower",
            funFact: "Goldfinches are strict vegetarians - one of the few songbirds that feed their young exclusively on seeds.",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .common,
            hasSexualDimorphism: true,
            maleDescription: "Brilliant yellow with black forehead, black wings with white bars (breeding); olive-drab in winter",
            femaleDescription: "Duller olive-yellow overall with blackish wings and white wing bars",
            seasonalPresence: [.yearRound],
            sizeCategory: .small,
            primaryColors: [.yellow, .black, .white],
            song: "A lively, twittering 'per-chick-o-ree' often given in undulating flight"
        ),
        Bird(
            id: "house_finch",
            commonName: "House Finch",
            scientificName: "Haemorhous mexicanus",
            family: "Fringillidae",
            order: "Passeriformes",
            description: "Originally a western bird, now abundant across North America thanks to released pet shop birds in 1940.",
            habitat: "Cities, suburbs, farms, and desert areas",
            diet: "Seeds, buds, and fruits",
            funFact: "Male House Finch color ranges from pale yellow to bright red depending on diet - females prefer the reddest males!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .common,
            hasSexualDimorphism: true,
            maleDescription: "Rosy red head, breast, and rump with streaked brown back and flanks",
            femaleDescription: "Plain grayish-brown with blurry streaks and no red coloring",
            seasonalPresence: [.yearRound],
            sizeCategory: .small,
            primaryColors: [.red, .brown, .gray],
            song: "A long, jumbled warbling song ending in a buzzy 'zheeer'"
        ),
        Bird(
            id: "purple_finch",
            commonName: "Purple Finch",
            scientificName: "Haemorhous purpureus",
            family: "Fringillidae",
            order: "Passeriformes",
            description: "Not actually purple but raspberry-dipped in appearance, often confused with House Finch.",
            habitat: "Coniferous and mixed forests, forest edges",
            diet: "Seeds, berries, buds, and nectar",
            funFact: "Roger Tory Peterson described the male as 'a sparrow dipped in raspberry juice.'",
            conservationStatus: .leastConcern,
            regions: [.northeast, .midwest, .northwest],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Raspberry-pink wash on head, breast, and back with unstreaked belly",
            femaleDescription: "Brown-streaked with a bold white eyebrow and ear patch",
            seasonalPresence: [.yearRound],
            sizeCategory: .small,
            primaryColors: [.red, .brown, .white],
            song: "A rich, fast warble without the buzzy ending of House Finch"
        ),

        // ── Waterfowl ─────────────────────────────────────────
        Bird(
            id: "mallard",
            commonName: "Mallard",
            scientificName: "Anas platyrhynchos",
            family: "Anatidae",
            order: "Anseriformes",
            description: "The most familiar wild duck in the world and ancestor of most domestic duck breeds.",
            habitat: "Ponds, lakes, rivers, marshes, and parks",
            diet: "Aquatic plants, seeds, insects, and small fish",
            funFact: "Only female Mallards quack! Males make a softer, raspy sound.",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .common,
            hasSexualDimorphism: true,
            maleDescription: "Iridescent green head, white neck ring, chestnut breast, and gray body with a curly black tail feather",
            femaleDescription: "Mottled brown all over with an orange-and-brown bill",
            seasonalPresence: [.yearRound],
            sizeCategory: .large,
            primaryColors: [.green, .brown, .iridescent],
            song: "The classic 'quack-quack-quack' (female) and a raspy 'raeb' (male)"
        ),
        Bird(
            id: "wood_duck",
            commonName: "Wood Duck",
            scientificName: "Aix sponsa",
            family: "Anatidae",
            order: "Anseriformes",
            description: "Often considered North America's most beautiful duck, with ornate multi-colored plumage.",
            habitat: "Wooded swamps, marshes, streams, and ponds near trees",
            diet: "Seeds, fruits, insects, and aquatic plants",
            funFact: "Day-old Wood Duck chicks jump from nest cavities up to 50 feet high, bouncing safely on the ground!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest, .northwest],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Ornate iridescent green-purple crested head, red eyes, chestnut breast with white flecks",
            femaleDescription: "Grayish-brown with a distinctive white teardrop eye patch",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.green, .purple, .brown, .iridescent],
            song: "A rising whistle 'jeeee' (male) and a loud 'oo-eek, oo-eek' (female)"
        ),
        Bird(
            id: "great_blue_heron",
            commonName: "Great Blue Heron",
            scientificName: "Ardea herodias",
            family: "Ardeidae",
            order: "Pelecaniformes",
            description: "A majestic wading bird standing up to 4.5 feet tall, a patient and skilled fish hunter.",
            habitat: "Shorelines, marshes, riverbanks, and lake edges",
            diet: "Fish, frogs, small mammals, and other small animals",
            funFact: "Great Blue Herons swallow their prey whole, and have been known to choke on fish that are too large!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .uncommon,
            hasSexualDimorphism: false,
            maleDescription: "Blue-gray body, long S-curved neck, dagger-like yellow bill, black plumes above the eye",
            femaleDescription: "Nearly identical to male, slightly smaller",
            seasonalPresence: [.yearRound],
            sizeCategory: .veryLarge,
            primaryColors: [.blue, .gray, .white],
            song: "A harsh, deep 'frahnk' or 'braak' - prehistoric sounding"
        ),

        // ── Sparrows ──────────────────────────────────────────
        Bird(
            id: "white_throated_sparrow",
            commonName: "White-throated Sparrow",
            scientificName: "Zonotrichia albicollis",
            family: "Passerellidae",
            order: "Passeriformes",
            description: "A handsome sparrow with a haunting whistled song, one of the most recognizable bird songs in North America.",
            habitat: "Forest edges, thickets, woodlands, and brushy areas",
            diet: "Seeds, insects, and berries",
            funFact: "This species has two color morphs (tan-striped and white-striped) that almost always mate with the opposite morph!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest],
            rarityTier: .common,
            hasSexualDimorphism: false,
            maleDescription: "Brown-streaked with bold black and white (or tan) head stripes, white throat, and yellow lores",
            femaleDescription: "Very similar to male; tan-striped morph is slightly buffer overall",
            seasonalPresence: [.fall, .winter, .spring],
            sizeCategory: .small,
            primaryColors: [.brown, .white, .yellow],
            song: "'Oh Sweet Canada Canada Canada' - a clear, whistled melody that's easy to learn"
        ),
        Bird(
            id: "song_sparrow",
            commonName: "Song Sparrow",
            scientificName: "Melospiza melodia",
            family: "Passerellidae",
            order: "Passeriformes",
            description: "One of the most adaptable and widespread sparrows, found in an incredible variety of habitats.",
            habitat: "Shrubs near water, gardens, marsh edges, and roadsides",
            diet: "Seeds, insects, and berries",
            funFact: "Song Sparrows learn their songs from neighboring males, creating local 'dialects' that vary by region!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .common,
            hasSexualDimorphism: false,
            maleDescription: "Brown-streaked with a central breast spot, pumps its tail in flight",
            femaleDescription: "Identical to male in plumage",
            seasonalPresence: [.yearRound],
            sizeCategory: .small,
            primaryColors: [.brown, .white, .gray],
            song: "Begins with 2-3 clear notes then a buzzy trill: 'Maids, maids, put-on-your-tea-kettle'"
        ),

        // ── Blackbirds & Orioles ──────────────────────────────
        Bird(
            id: "red_winged_blackbird",
            commonName: "Red-winged Blackbird",
            scientificName: "Agelaius phoeniceus",
            family: "Icteridae",
            order: "Passeriformes",
            description: "One of the most abundant birds in North America, a marsh-dwelling icon of spring.",
            habitat: "Marshes, wet meadows, fields, and roadsides",
            diet: "Seeds and insects",
            funFact: "A single male may have up to 15 mates, each nesting in his territory! He's one of the most polygynous birds.",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .common,
            hasSexualDimorphism: true,
            maleDescription: "Jet black with brilliant red and yellow shoulder patches (epaulets)",
            femaleDescription: "Dark brown with heavy streaking - looks like a completely different species",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.black, .red, .yellow],
            song: "A liquid, gurgling 'conk-la-reeee!' from marsh perches"
        ),
        Bird(
            id: "baltimore_oriole",
            commonName: "Baltimore Oriole",
            scientificName: "Icterus galbula",
            family: "Icteridae",
            order: "Passeriformes",
            description: "A stunning orange and black songbird that weaves remarkable hanging pouch nests.",
            habitat: "Open deciduous woodlands, orchards, and shade trees in parks",
            diet: "Insects, nectar, and fruits (especially oranges and grape jelly!)",
            funFact: "Their pendulous nests can hang up to 8 inches deep and take up to 2 weeks to weave!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .midwest, .greatPlains],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Flaming orange body with a black hood, back, and wings with white wing bars",
            femaleDescription: "Yellowish-orange and olive with grayish wings and variable dark on head",
            seasonalPresence: [.spring, .summer],
            sizeCategory: .medium,
            primaryColors: [.orange, .black, .white],
            song: "A rich, fluty series of paired whistles that's bright and cheerful"
        ),

        // ── Chickadees & Titmice ──────────────────────────────
        Bird(
            id: "black_capped_chickadee",
            commonName: "Black-capped Chickadee",
            scientificName: "Poecile atricapillus",
            family: "Paridae",
            order: "Passeriformes",
            description: "A bold, curious bird that readily comes to feeders and will eat from your hand with patience.",
            habitat: "Deciduous and mixed forests, parks, and suburbs",
            diet: "Insects, seeds, and berries",
            funFact: "Chickadees can lower their body temperature by 10-12°F at night to conserve energy in winter!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .midwest, .northwest],
            rarityTier: .common,
            hasSexualDimorphism: false,
            maleDescription: "Black cap and bib, white cheeks, gray back, and buffy flanks",
            femaleDescription: "Identical to male in plumage",
            seasonalPresence: [.yearRound],
            sizeCategory: .small,
            primaryColors: [.black, .white, .gray],
            song: "The namesake 'chick-a-dee-dee-dee' call and a clear 'fee-bee' whistle"
        ),
        Bird(
            id: "tufted_titmouse",
            commonName: "Tufted Titmouse",
            scientificName: "Baeolophus bicolor",
            family: "Paridae",
            order: "Passeriformes",
            description: "A perky, crested bird with big dark eyes, bold and curious at bird feeders.",
            habitat: "Deciduous forests, parks, and suburban areas",
            diet: "Insects, seeds, nuts, and berries",
            funFact: "Tufted Titmice hoard food in fall, hiding seeds in bark crevices, and can remember hundreds of cache locations!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest],
            rarityTier: .common,
            hasSexualDimorphism: false,
            maleDescription: "Gray above, white below with rusty flanks, pointed gray crest, and large dark eyes",
            femaleDescription: "Identical to male in plumage",
            seasonalPresence: [.yearRound],
            sizeCategory: .small,
            primaryColors: [.gray, .white, .orange],
            song: "A clear, whistled 'peter-peter-peter' repeated insistently"
        ),

        // ── Nuthatches ────────────────────────────────────────
        Bird(
            id: "white_breasted_nuthatch",
            commonName: "White-breasted Nuthatch",
            scientificName: "Sitta carolinensis",
            family: "Sittidae",
            order: "Passeriformes",
            description: "The 'upside-down bird' that walks headfirst down tree trunks searching for insects.",
            habitat: "Deciduous forests, woodlands, and suburbs with large trees",
            diet: "Insects, seeds, and nuts",
            funFact: "Nuthatches sweep crushed insects around their nest entrance - the chemicals may deter squirrels!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .common,
            hasSexualDimorphism: true,
            maleDescription: "Blue-gray above, white face and underparts, black cap, and rusty under-tail",
            femaleDescription: "Similar but with a gray cap instead of black",
            seasonalPresence: [.yearRound],
            sizeCategory: .small,
            primaryColors: [.blue, .white, .black],
            song: "A nasal, laughing 'ha-ha-ha-ha' and a soft 'yank-yank'"
        ),

        // ── Wrens ─────────────────────────────────────────────
        Bird(
            id: "carolina_wren",
            commonName: "Carolina Wren",
            scientificName: "Thryothorus ludovicianus",
            family: "Troglodytidae",
            order: "Passeriformes",
            description: "A small but astonishingly loud bird that belts out its song from deep in tangled underbrush.",
            habitat: "Dense undergrowth in forests, thickets, and suburban gardens",
            diet: "Insects, spiders, and some seeds",
            funFact: "Males have a repertoire of 25-40 different song types, and mated pairs sing duets!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest],
            rarityTier: .common,
            hasSexualDimorphism: false,
            maleDescription: "Rich rusty-brown above, warm buffy below, bold white eyebrow stripe, upturned tail",
            femaleDescription: "Identical to male in plumage",
            seasonalPresence: [.yearRound],
            sizeCategory: .small,
            primaryColors: [.brown, .white],
            song: "A ringing, three-part 'teakettle-teakettle-teakettle!' that's amazingly loud for such a tiny bird"
        ),

        // ── Shorebirds ───────────────────────────────────────
        Bird(
            id: "killdeer",
            commonName: "Killdeer",
            scientificName: "Charadrius vociferus",
            family: "Charadriidae",
            order: "Charadriiformes",
            description: "A clever shorebird that nests in parking lots and performs a convincing 'broken wing' act to lure predators away.",
            habitat: "Fields, parking lots, rooftops, and shorelines",
            diet: "Insects, earthworms, and small invertebrates",
            funFact: "When a predator approaches the nest, Killdeer fake a broken wing to lead the threat away, then fly off!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .common,
            hasSexualDimorphism: false,
            maleDescription: "Brown above, white below, with two bold black breast bands, orange rump visible in flight",
            femaleDescription: "Nearly identical to male",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.brown, .white, .black],
            song: "A piercing, insistent 'kill-deer! kill-deer!' that gives it its name"
        ),

        // ── Swallows ──────────────────────────────────────────
        Bird(
            id: "barn_swallow",
            commonName: "Barn Swallow",
            scientificName: "Hirundo rustica",
            family: "Hirundinidae",
            order: "Passeriformes",
            description: "The most widespread swallow in the world, recognized by its deeply forked tail and acrobatic flight.",
            habitat: "Open areas near water, farms, fields, and under bridges",
            diet: "Flying insects caught on the wing",
            funFact: "Barn Swallows drink and bathe while flying, skimming the water surface without stopping!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .common,
            hasSexualDimorphism: true,
            maleDescription: "Deep blue-black above, rusty-orange forehead and throat, buff to cinnamon underparts, long forked tail",
            femaleDescription: "Similar but paler below with a shorter tail fork",
            seasonalPresence: [.spring, .summer],
            sizeCategory: .small,
            primaryColors: [.blue, .orange, .black],
            song: "A cheerful, twittering warble interspersed with a dry rattle"
        ),

        // ── Tanagers ──────────────────────────────────────────
        Bird(
            id: "scarlet_tanager",
            commonName: "Scarlet Tanager",
            scientificName: "Piranga olivacea",
            family: "Cardinalidae",
            order: "Passeriformes",
            description: "A breathtaking scarlet-and-black bird that's surprisingly hard to spot high in the forest canopy.",
            habitat: "Mature deciduous forest interior and large forest tracts",
            diet: "Insects and berries",
            funFact: "Despite being brilliantly colored, they spend most of their time hidden in the treetops and are heard far more often than seen!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest],
            rarityTier: .rare,
            hasSexualDimorphism: true,
            maleDescription: "Brilliant scarlet-red body with jet-black wings and tail",
            femaleDescription: "Olive-yellow-green overall with darker olive wings",
            seasonalPresence: [.spring, .summer],
            sizeCategory: .medium,
            primaryColors: [.red, .black],
            song: "A burry, robin-like song often described as 'a robin with a sore throat'"
        ),

        // ── Kingfishers ──────────────────────────────────────
        Bird(
            id: "belted_kingfisher",
            commonName: "Belted Kingfisher",
            scientificName: "Megaceryle alcyon",
            family: "Alcedinidae",
            order: "Coraciiformes",
            description: "A stocky, large-headed bird that plunges headfirst into water to catch fish.",
            habitat: "Streams, rivers, ponds, lakes, and estuaries",
            diet: "Fish, crayfish, and aquatic invertebrates",
            funFact: "Unusually for birds, the female is more colorful than the male, sporting an extra rusty belly band!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Blue-gray above with a shaggy crest, white collar, and single blue breast band",
            femaleDescription: "Like male but with an additional rusty-brown belly band - the more colorful sex!",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.blue, .white, .gray],
            song: "A loud, dry, rattling call that carries over water"
        ),

        // ── Unique & Rare Species ─────────────────────────────
        Bird(
            id: "painted_bunting",
            commonName: "Painted Bunting",
            scientificName: "Passerina ciris",
            family: "Cardinalidae",
            order: "Passeriformes",
            description: "Perhaps the most colorful songbird in North America, like a living rainbow.",
            habitat: "Thickets, woodland edges, and overgrown fields",
            diet: "Seeds and insects",
            funFact: "They were once so popular as cage birds that trapping significantly reduced their numbers!",
            conservationStatus: .nearThreatened,
            regions: [.southeast, .texas],
            rarityTier: .rare,
            hasSexualDimorphism: true,
            maleDescription: "Indigo-blue head, green back, and brilliant red underparts - impossibly colorful",
            femaleDescription: "Bright lime-green overall, one of the greenest songbirds in North America",
            seasonalPresence: [.spring, .summer],
            sizeCategory: .small,
            primaryColors: [.blue, .green, .red],
            song: "A sweet, musical warble that's pleasant but not as spectacular as its plumage"
        ),
        Bird(
            id: "snowy_owl",
            commonName: "Snowy Owl",
            scientificName: "Bubo scandiacus",
            family: "Strigidae",
            order: "Strigiformes",
            description: "A magnificent Arctic predator that occasionally irrupts southward in winter, thrilling birders everywhere.",
            habitat: "Arctic tundra; in winter, open fields, airports, shorelines, and dunes",
            diet: "Lemmings and other rodents, rabbits, and birds",
            funFact: "Unlike most owls, Snowy Owls hunt during the day, which makes sense given 24-hour Arctic daylight!",
            conservationStatus: .vulnerable,
            regions: [.northeast, .midwest, .northwest, .alaska],
            rarityTier: .veryRare,
            hasSexualDimorphism: true,
            maleDescription: "Nearly pure white with a few dark spots, becoming whiter with age, bright yellow eyes",
            femaleDescription: "White with extensive dark barring across the body, never becomes fully white",
            seasonalPresence: [.winter],
            sizeCategory: .veryLarge,
            primaryColors: [.white, .black, .yellow],
            song: "A deep, booming hoot on the breeding grounds; mostly silent in winter"
        ),
        Bird(
            id: "california_condor",
            commonName: "California Condor",
            scientificName: "Gymnogyps californianus",
            family: "Cathartidae",
            order: "Cathartiformes",
            description: "The largest flying land bird in North America, brought back from the very brink of extinction.",
            habitat: "Rugged mountain terrain, gorges, and open grasslands",
            diet: "Carrion (dead animals)",
            funFact: "In 1987, only 27 California Condors existed. Thanks to captive breeding, there are now over 500!",
            conservationStatus: .criticallyEndangered,
            regions: [.california, .southwest],
            rarityTier: .legendary,
            hasSexualDimorphism: false,
            maleDescription: "Massive black body with white wing patches, bare reddish-orange head, 9.5-foot wingspan",
            femaleDescription: "Identical to male in plumage, slightly smaller",
            seasonalPresence: [.yearRound],
            sizeCategory: .veryLarge,
            primaryColors: [.black, .white, .orange],
            song: "Mostly silent; makes hisses and grunts at roost sites"
        ),
        Bird(
            id: "whooping_crane",
            commonName: "Whooping Crane",
            scientificName: "Grus americana",
            family: "Gruidae",
            order: "Gruiformes",
            description: "North America's tallest bird and one of the rarest, the subject of one of conservation's greatest success stories.",
            habitat: "Marshes, prairie potholes, and coastal flats",
            diet: "Blue crabs, clams, frogs, and aquatic plants",
            funFact: "Down to just 21 birds in 1941, ultralight aircraft were used to teach captive-raised chicks their migration route!",
            conservationStatus: .endangered,
            regions: [.texas, .greatPlains, .midwest],
            rarityTier: .legendary,
            hasSexualDimorphism: false,
            maleDescription: "Tall, snow-white with black wingtips, bare red crown, and long dark legs",
            femaleDescription: "Identical to male, slightly smaller",
            seasonalPresence: [.winter, .spring],
            sizeCategory: .veryLarge,
            primaryColors: [.white, .black, .red],
            song: "A loud, trumpeting 'ker-LOO' that can carry for miles"
        ),
        Bird(
            id: "atlantic_puffin",
            commonName: "Atlantic Puffin",
            scientificName: "Fratercula arctica",
            family: "Alcidae",
            order: "Charadriiformes",
            description: "The beloved 'clown of the sea' with its colorful bill and charming upright posture.",
            habitat: "Ocean waters and rocky coastal islands for nesting",
            diet: "Small fish, especially sand eels and herring",
            funFact: "Puffins can hold 10+ fish crosswise in their bill at once thanks to backward-pointing spines on their tongue!",
            conservationStatus: .vulnerable,
            regions: [.northeast],
            rarityTier: .veryRare,
            hasSexualDimorphism: false,
            maleDescription: "Black back, white underparts, white face, and a large triangular bill of red, yellow, and blue",
            femaleDescription: "Identical to male, marginally smaller bill",
            seasonalPresence: [.spring, .summer],
            sizeCategory: .medium,
            primaryColors: [.black, .white, .orange, .red],
            song: "A low growling 'arrr-uh' from the nesting burrow"
        ),

        // ── More Common Species ───────────────────────────────
        Bird(
            id: "mourning_dove",
            commonName: "Mourning Dove",
            scientificName: "Zenaida macroura",
            family: "Columbidae",
            order: "Columbiformes",
            description: "A graceful, slender bird whose soft cooing is a familiar sound across the continent.",
            habitat: "Open woodlands, farms, suburbs, and parks",
            diet: "Seeds and grains",
            funFact: "Mourning Doves can store up to 17,200 seeds in their crop and digest them later!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .common,
            hasSexualDimorphism: true,
            maleDescription: "Soft gray-brown with iridescent neck patches, black spots on wings, and long pointed tail",
            femaleDescription: "Similar but slightly less iridescent and more uniformly colored",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.brown, .gray],
            song: "A mournful, owlish cooing: 'cooOOoo-woo-woo-woo'"
        ),
        Bird(
            id: "dark_eyed_junco",
            commonName: "Dark-eyed Junco",
            scientificName: "Junco hyemalis",
            family: "Passerellidae",
            order: "Passeriformes",
            description: "The 'snowbird' that appears at feeders when winter arrives, flashing white outer tail feathers.",
            habitat: "Coniferous and mixed forests; in winter, thickets, gardens, and parks",
            diet: "Seeds and insects",
            funFact: "Dark-eyed Juncos come in several distinct color forms, from slate-colored to Oregon to pink-sided!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .common,
            hasSexualDimorphism: true,
            maleDescription: "Slate-gray hood, back, and wings with a white belly and pink bill; white outer tail feathers",
            femaleDescription: "Similar pattern but browner and paler overall, less contrast",
            seasonalPresence: [.yearRound],
            sizeCategory: .small,
            primaryColors: [.gray, .white, .brown],
            song: "A musical trill on one pitch and a sharp 'tick' note; flashing white tail feathers in flight"
        ),
        Bird(
            id: "northern_mockingbird",
            commonName: "Northern Mockingbird",
            scientificName: "Mimus polyglottos",
            family: "Mimidae",
            order: "Passeriformes",
            description: "An incredibly talented mimic that can learn over 200 different songs in its lifetime.",
            habitat: "Towns, suburbs, parks, forest edges, and open land with bushes",
            diet: "Insects, berries, and fruits",
            funFact: "Unmated males may sing all night long under bright lights, cycling through their entire repertoire!",
            conservationStatus: .leastConcern,
            regions: [.southeast, .southwest, .texas, .california, .midwest],
            rarityTier: .common,
            hasSexualDimorphism: false,
            maleDescription: "Gray above, whitish below, with two white wing bars and white outer tail feathers; long tail",
            femaleDescription: "Essentially identical to male",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.gray, .white],
            song: "An endlessly varied mimic that repeats each phrase 3+ times before switching - the ultimate copycat"
        ),
        Bird(
            id: "cedar_waxwing",
            commonName: "Cedar Waxwing",
            scientificName: "Bombycilla cedrorum",
            family: "Bombycillidae",
            order: "Passeriformes",
            description: "An elegant, sleek bird with a black mask and waxy red wingtips, traveling in sociable flocks.",
            habitat: "Woodlands, orchards, parks, and areas with berry-producing trees",
            diet: "Berries and insects",
            funFact: "Cedar Waxwings sometimes become intoxicated from eating fermented berries and can't fly straight!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .uncommon,
            hasSexualDimorphism: false,
            maleDescription: "Silky brown with a black mask, yellow belly band, waxy red wingtips, and yellow-tipped tail",
            femaleDescription: "Nearly identical to male, slightly less defined markings",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.brown, .yellow, .red],
            song: "A very high-pitched, thin 'sreeee' whistle - almost at the edge of human hearing"
        ),
        Bird(
            id: "indigo_bunting",
            commonName: "Indigo Bunting",
            scientificName: "Passerina cyanea",
            family: "Cardinalidae",
            order: "Passeriformes",
            description: "A dazzling blue songbird that isn't actually blue - its color comes from microscopic feather structures refracting light.",
            habitat: "Brushy edges, clearings, roadsides, and overgrown fields",
            diet: "Seeds, insects, and berries",
            funFact: "Indigo Buntings migrate at night using the stars for navigation. They learn the star patterns as juveniles!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest, .greatPlains],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Entirely vivid indigo-blue, appearing black in poor light",
            femaleDescription: "Plain brown with faint streaking, sometimes with a hint of blue on tail",
            seasonalPresence: [.spring, .summer],
            sizeCategory: .small,
            primaryColors: [.blue],
            song: "Rapid, bright paired phrases: 'fire-fire, where-where, here-here, see-it-see-it'"
        ),

        // ── Flycatchers ──────────────────────────────────────
        Bird(
            id: "eastern_phoebe",
            commonName: "Eastern Phoebe",
            scientificName: "Sayornis phoebe",
            family: "Tyrannidae",
            order: "Passeriformes",
            description: "A tail-wagging flycatcher that nests on human structures and was the first banded bird in North America.",
            habitat: "Open woodlands near water, bridges, porches, and barns",
            diet: "Flying insects",
            funFact: "John James Audubon tied silver thread to an Eastern Phoebe's leg in 1803 - the first bird banding in America!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest],
            rarityTier: .common,
            hasSexualDimorphism: false,
            maleDescription: "Dark gray-brown above, whitish below, with a dark head; constantly wags tail",
            femaleDescription: "Identical to male",
            seasonalPresence: [.spring, .summer, .fall],
            sizeCategory: .small,
            primaryColors: [.gray, .white, .brown],
            song: "A raspy, emphatic 'fee-BEE' repeated from an exposed perch"
        ),

        // ── Vireos ────────────────────────────────────────────
        Bird(
            id: "red_eyed_vireo",
            commonName: "Red-eyed Vireo",
            scientificName: "Vireo olivaceus",
            family: "Vireonidae",
            order: "Passeriformes",
            description: "One of the most common forest birds that sings virtually non-stop from dawn to dusk.",
            habitat: "Deciduous forest canopy and mature woodlands",
            diet: "Insects and berries",
            funFact: "One Red-eyed Vireo was recorded singing 22,197 songs in a single day!",
            conservationStatus: .leastConcern,
            regions: [.northeast, .southeast, .midwest, .greatPlains],
            rarityTier: .common,
            hasSexualDimorphism: false,
            maleDescription: "Olive-green above, white below, with a gray cap, white eyebrow, dark eye-line, and red iris",
            femaleDescription: "Identical to male in plumage",
            seasonalPresence: [.spring, .summer],
            sizeCategory: .small,
            primaryColors: [.green, .white, .gray],
            song: "Endless short musical phrases separated by pauses, like a never-ending conversation"
        ),

        // ── Tropical / Southern ───────────────────────────────
        Bird(
            id: "roseate_spoonbill",
            commonName: "Roseate Spoonbill",
            scientificName: "Platalea ajaja",
            family: "Threskiornithidae",
            order: "Pelecaniformes",
            description: "A stunning pink wading bird with a bizarre spoon-shaped bill, often mistaken for a flamingo.",
            habitat: "Mangroves, tidal flats, marshes, and shallow coastal lagoons",
            diet: "Small fish, shrimp, aquatic insects, and crustaceans",
            funFact: "Their pink color comes from the carotenoid pigments in the crustaceans they eat, similar to flamingos!",
            conservationStatus: .leastConcern,
            regions: [.florida, .texas, .southeast],
            rarityTier: .rare,
            hasSexualDimorphism: false,
            maleDescription: "Pink plumage with deeper pink wings, bald greenish head, and a flattened spoon-shaped bill",
            femaleDescription: "Very similar to male, slightly smaller",
            seasonalPresence: [.yearRound],
            sizeCategory: .veryLarge,
            primaryColors: [.red, .white, .green],
            song: "Mostly silent; occasional low grunting 'huh-huh-huh' at the colony"
        ),
        Bird(
            id: "magnificent_frigatebird",
            commonName: "Magnificent Frigatebird",
            scientificName: "Fregata magnificens",
            family: "Fregatidae",
            order: "Suliformes",
            description: "A master of soaring flight with a dramatic red throat pouch, a pirate of the tropical skies.",
            habitat: "Tropical coastlines, open ocean, and coastal lagoons",
            diet: "Fish snatched from the surface or stolen from other seabirds",
            funFact: "Males inflate their red throat pouch like a balloon to attract females, taking 20 minutes to fully inflate!",
            conservationStatus: .leastConcern,
            regions: [.florida, .texas],
            rarityTier: .rare,
            hasSexualDimorphism: true,
            maleDescription: "All black with a glossy purple-green sheen and an inflatable red throat pouch",
            femaleDescription: "Black with a white breast and no red throat pouch",
            seasonalPresence: [.yearRound],
            sizeCategory: .veryLarge,
            primaryColors: [.black, .red],
            song: "Males produce a drumming/rattling bill-clapping during display; otherwise silent"
        ),

        // ── Hawaiian Species ──────────────────────────────────
        Bird(
            id: "nene",
            commonName: "Nene (Hawaiian Goose)",
            scientificName: "Branta sandvicensis",
            family: "Anatidae",
            order: "Anseriformes",
            description: "Hawaii's state bird, evolved from Canada Geese that landed in Hawaii about 500,000 years ago.",
            habitat: "Volcanic slopes, grasslands, and coastal dunes in Hawaii",
            diet: "Grasses, herbs, and shrub leaves and berries",
            funFact: "Nene have reduced webbing on their feet compared to other geese, an adaptation for walking on lava flows!",
            conservationStatus: .vulnerable,
            regions: [.hawaii],
            rarityTier: .veryRare,
            hasSexualDimorphism: false,
            maleDescription: "Buff-brown body with black face, furrowed neck feathers, and partially webbed feet",
            femaleDescription: "Similar to male, slightly smaller",
            seasonalPresence: [.yearRound],
            sizeCategory: .large,
            primaryColors: [.brown, .black, .white],
            song: "A soft, moaning 'nay-nay' that gives the bird its Hawaiian name"
        ),

        // ── Alaska Species ────────────────────────────────────
        Bird(
            id: "willow_ptarmigan",
            commonName: "Willow Ptarmigan",
            scientificName: "Lagopus lagopus",
            family: "Phasianidae",
            order: "Galliformes",
            description: "Alaska's state bird that changes plumage from brown to pure white with the seasons.",
            habitat: "Arctic and subarctic tundra, willow thickets, and alpine meadows",
            diet: "Willow buds, berries, leaves, and insects",
            funFact: "In winter, Willow Ptarmigan grow feathers on their feet that act as snowshoes!",
            conservationStatus: .leastConcern,
            regions: [.alaska],
            rarityTier: .rare,
            hasSexualDimorphism: true,
            maleDescription: "Mottled brown in summer, pure white in winter with red combs above eyes",
            femaleDescription: "More finely barred brown in summer, white in winter, smaller red combs",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.brown, .white, .red],
            song: "A loud, cackling 'go-BACK, go-BACK, go-back-back-back'"
        ),

        // ── More Raptors ─────────────────────────────────────
        Bird(
            id: "american_kestrel",
            commonName: "American Kestrel",
            scientificName: "Falco sparverius",
            family: "Falconidae",
            order: "Falconiformes",
            description: "North America's smallest and most colorful falcon, often seen hovering over roadsides.",
            habitat: "Open fields, grasslands, deserts, and urban areas",
            diet: "Insects, small rodents, and small birds",
            funFact: "American Kestrels can see ultraviolet light, allowing them to detect the UV-reflecting urine trails of voles!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Blue-gray wings, rusty back and tail, two black face stripes, spotted breast",
            femaleDescription: "Rusty-brown wings and back with dark barring, streaked breast",
            seasonalPresence: [.yearRound],
            sizeCategory: .medium,
            primaryColors: [.blue, .brown, .white],
            song: "A rapid, high-pitched 'klee-klee-klee-klee' alarm call"
        ),
        Bird(
            id: "osprey",
            commonName: "Osprey",
            scientificName: "Pandion haliaetus",
            family: "Pandionidae",
            order: "Accipitriformes",
            description: "A spectacular fish hawk that plunges feet-first into water, found on every continent except Antarctica.",
            habitat: "Near rivers, lakes, reservoirs, and coastal waters",
            diet: "Almost exclusively live fish",
            funFact: "Ospreys have reversible outer toes and barbed foot pads - special adaptations for gripping slippery fish!",
            conservationStatus: .leastConcern,
            regions: [.nationwide],
            rarityTier: .uncommon,
            hasSexualDimorphism: true,
            maleDescription: "Dark brown above, white below, with a white head and dark eye stripe",
            femaleDescription: "Similar but often with a darker 'necklace' of breast streaks",
            seasonalPresence: [.spring, .summer, .fall],
            sizeCategory: .large,
            primaryColors: [.brown, .white],
            song: "A series of sharp, whistled 'cheep-cheep-cheep' calls near the nest"
        ),
    ]
}
